name: predict_1x2_ai
description: "AI-powered sports predictions app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  percent_indicator: ^4.2.3
  http: ^1.1.0
  intl: ^0.19.0
  google_generative_ai: ^0.4.0
  flutter_dotenv: ^5.1.0
  path_provider: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png  # Burası görseldeki logonun yolu olmalı
    - assets/matches_data.json  # Bunu mutlaka ekle!
    - assets/.env
